
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'peru_archaeology' # This is the internal name used for compiling SQL
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'jaffle_shop'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models


models:
  peru_archaeology: # Matches the name: config at the top of this file
    
    # --- STAGING LAYER ---
    # Points to: models/staging/
    staging:
      +database: stg-peru-archaeology       # Writes clean views to your Staging BQ project
      +schema: staging                      # Creates dataset: <target>_staging
      +materialized: view                   # Keeps views lightweight & dynamic

    # --- MARTS LAYER ---
    # Points to: models/marts/
    marts:
      +database: peru-archaeology           # Writes production tables to your Marts BQ project
      +schema: core                         # Creates dataset: <target>_core
      +materialized: table                  # Materialized as tables for fast query performance

    